### ISSUE TITLE
6.0m11 release checklist

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-maestro#123]
It's been long enough wait since the last milestone. Let's put out 6.0m11!

Checklist:

 * [x] Add screenshots to devguide for enabling SourceLink
 * [x] Regenerate NuGet API key for publishing and update `appveyor.yml` with new key
    * [x] Do a test "pre-final" tag to verify new nuget packages are being published
 * [x] FIXME: Why is API reference now empty???
 * [x] Update docfx site content on `gh-pages` branch once all pending site content has been finalized
 * [x] Move current docfx site content on `gh-pages` branch to `archive/6.0m8` subdirectory. Make sure new docfx content links to this older version on landing page
 * [ ] LocalConfigure.exe fails to run on Maestro startup
![2022-08-03 00_37_43-C__Program Files_OSGeo_MapGuide Maestro 6 0m11_LocalConfigure exe](https://user-images.githubusercontent.com/563860/182402516-393c557e-fbd5-48c7-9fb8-223f0b4c3c5d.png)
 * [x] MgCooker shortcut still created in installer
 * [x] Don't install under OSGeo sub-folder (we are not an OSGeo-affiliated project)
